
package webServiceEx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebSB", targetNamespace = "sb.gel.com", wsdlLocation = "http://95.68.244.58:888/sb/ws/WebSB?wsdl")
public class WebSB
    extends Service
{

    private final static URL WEBSB_WSDL_LOCATION;
    private final static WebServiceException WEBSB_EXCEPTION;
    private final static QName WEBSB_QNAME = new QName("sb.gel.com", "WebSB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://95.68.244.58:888/sb/ws/WebSB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSB_WSDL_LOCATION = url;
        WEBSB_EXCEPTION = e;
    }

    public WebSB() {
        super(__getWsdlLocation(), WEBSB_QNAME);
    }

    public WebSB(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSB_QNAME, features);
    }

    public WebSB(URL wsdlLocation) {
        super(wsdlLocation, WEBSB_QNAME);
    }

    public WebSB(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSB_QNAME, features);
    }

    public WebSB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebSB(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebSBPortType
     */
    @WebEndpoint(name = "WebSBSoap")
    public WebSBPortType getWebSBSoap() {
        return super.getPort(new QName("sb.gel.com", "WebSBSoap"), WebSBPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebSBPortType
     */
    @WebEndpoint(name = "WebSBSoap")
    public WebSBPortType getWebSBSoap(WebServiceFeature... features) {
        return super.getPort(new QName("sb.gel.com", "WebSBSoap"), WebSBPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSB_EXCEPTION!= null) {
            throw WEBSB_EXCEPTION;
        }
        return WEBSB_WSDL_LOCATION;
    }

}
