
package webServiceEx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebSBPortType", targetNamespace = "sb.gel.com")
@XmlSeeAlso({
    //ru._1c.v8._8_1.data.core.ObjectFactory.class,
    //com.gel.sb.ObjectFactory.class,
    //ru._1c.v8._8_1.data.enterprise.ObjectFactory.class,
    //ru._1c.v8._8_1.data.txtedt.ObjectFactory.class,
    //ru._1c.v8._8_1.data.ui.ObjectFactory.class
})
public interface WebSBPortType {


    /**
     * 
     * @param pin
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "sb.gel.com#WebSB:newGame")
    @WebResult(targetNamespace = "sb.gel.com")
    @RequestWrapper(localName = "newGame", targetNamespace = "sb.gel.com", className = "com.gel.sb.NewGame")
    @ResponseWrapper(localName = "newGameResponse", targetNamespace = "sb.gel.com", className = "com.gel.sb.NewGameResponse")
    public String newGame(
        @WebParam(name = "pin", targetNamespace = "sb.gel.com")
        String pin);

}
